run_name: 'graph_16_2'
dataset: 'cifar' #'cifar', 'mnist'
aggregation: 'inplace' #'inplace', 'score', 'score_validation', 'approach_2'
#topology: './conf/topologies/graph_16_2/custom_1.yaml'
runtime: './runtime.yaml'
split_dataset: 'prepare_dataset_iid_train_common_test' #'prepare_dataset_iid_train_common_test', 'prepare_dataset_niid_train_common_test', 'skew_class_niid_train_common_test', 'skew_class_niid_train_niid_test', 'prepare_dataset_iid_train_iid_test', 'prepare_dataset_niid_train_iid_test', 'prepare_dataset_niid_train_niid_test', 'prepare_dataset_niid_class_partition'
device: cpu
num_rounds: 1024
warmup_rounds: 0
warmup_epochs: 15
batch_size: 64
num_classes: 10 #output layer size
seed: 1999
config_fit:
  lr: 0.0001
  momentum: 0.9
  local_epochs: 4
