run_name: '0'
topology: './conf/topologies/custom_2.yaml'
device: GPU
early_local_train: False
num_rounds: 1020
# num_clients_per_round_fit: 2 #Doesn't matter - controlled by topology
# num_clients_per_round_eval: 2 #Doesn't matter - controlled by topology
batch_size: 128
num_classes: 10 #10 output layer size
balance_data: False
seed: 2001
config_fit:
  lr: 0.0001
  momentum: 0.9
  local_epochs: 32
